spring:
  datasource:
    url: jdbc:mysql://192.168.239.128:3306/zmb_book_store?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: password